# Xamarin.Android and Xamarin.iOS
# Build a Xamarin.Android and Xamarin.iOS app.
# Add steps that test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

jobs:

- job: BuildApp
  pool:
    vmImage: 'macOS 10.13'

  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

  steps:

  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_4_1 
    displayName: 'Select Xamarin SDK version'
    enabled: false


  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'


  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'

  - task: AndroidSigning@3
    inputs:
      apkFiles: '$(outputDirectory)/*.apk'
      apksignerKeystoreFile: 'FifteenPercent15.keystore'
      apksignerKeystorePassword: '$(keystorepass)'
      apksignerKeystoreAlias: 'fifteenpercentalias'
      apksignerKeyPassword: '$(keyaliaspass)'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'Fifteen_Percent_Ad_Hoc.mobileprovision'
      removeProfile: false

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Certificates15.p12'
      certPwd: '$(p12password)'
      keychain: 'temp'
  - task: XamariniOS@2
    inputs:
      solutionFile: '**/*iOS.csproj'
      configuration: '$(buildConfiguration)'
      packageApp: true
      runNugetRestore: false
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'App Center'
      appSlug: 'Lachlan-Gordon/FifteenPercentDrop'
      appFile: '**/*.ipa'
      releaseNotesOption: 'input'
      releaseNotesInput: '15 % drop app'
      destinationType: 'groups'
      
  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'App Center'
      appSlug: 'Lachlan-Gordon/FifteenPercentDropDroid'
      appFile: '$(outputDirectory)/*.apk'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      releaseNotesInput: 'this is my new app'
      destinationType: 'groups'

  



